# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Azure Meetup Milano
email: azuremeetupmilano@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Questo gruppo è per tutti quelli che si interessano di Cloud computing ed in particolare dei servizi offerti da Microsoft Azure.
  Gli incontri spaziano da sessione molto tecniche a experience report di più' alto livello, da demo di nuovi e vecchi servizi a war/horror stories dal campo.
  Essendo l'aspetto principale Azure i temi trattati non sono solo strettamente .NET/Windows ma includono qualsiasi tecnologia che beneficia di un approccio cloud-centrico.
  Chi dovrebbe unirsi a noi: chiunque sia interessato ad Azure, IaaS, PaaS, FaaS, SaaS, sviluppatori (java, python, node.js, .net, nosql, sql, ops, tutti sono i benvenuti), professionisti IT, big data (Hadoop, Spark, Hive, HBase, Pig, etc), Cognitive services e gli interessati al mondo cloud in generale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: azuremeetupmilano
github_username:  azuremeetupmilano

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
